name: Node-CI Beta

on:
  push:
    branches: [beta-*.*.*, beta]
  workflow_dispatch:

jobs:
  build_and_test:
    uses: homebridge/.github/.github/workflows/nodejs-build-and-test.yml@latest
    with:
      enable_coverage: false
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  lint:
    needs: build_and_test
    uses: homebridge/.github/.github/workflows/eslint.yml@latest

  publish:
    needs: lint

    if: ${{ github.repository == 'homebridge/plugin-ui-utils' }}

    uses: homebridge/.github/.github/workflows/npm-publish.yml@latest
    with:
      tag: beta
      dynamically_adjust_version: true
      npm_version_command: pre
      pre_id: beta
    secrets:
      npm_auth_token: ${{ secrets.npm_token }}

  github-releases-to-discord:
    uses: homebridge/.github/.github/workflows/discord-webhooks.yml@latest
    with:
      footer_title: "plugin-ui-utils"
    secrets:
      DISCORD_WEBHOOK_URL_BETA: ${{ secrets.DISCORD_WEBHOOK_URL_LATEST }}
