name: Node Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build_and_test:
    uses: homebridge/.github/.github/workflows/nodejs-build-and-test.yml@latest
    with:
      enable_coverage: false
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: build_and_test

    if: ${{ github.repository == 'homebridge/plugin-ui-utils' }}

    uses: homebridge/.github/.github/workflows/npm-publish-esm.yml@latest
    secrets:
      npm_auth_token: ${{ secrets.npm_token }}

#  github-releases-to-discord:
#    name: Discord Webhooks
#    needs: publish
#    uses: homebridge/.github/.github/workflows/discord-webhooks.yml@latest
#    with:
#      title: Plugin UI Utils
#      description: |
#        Version `v${{ needs.publish.outputs.NPM_VERSION }}`
#      url: 'https://github.com/homebridge/plugin-ui-utils/releases/tag/v${{ needs.publish.outputs.NPM_VERSION }}'
#    secrets:
#      DISCORD_WEBHOOK_URL_LATEST: ${{ secrets.DISCORD_WEBHOOK_URL_LATEST }}
